name: WindowsBuildOnly

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019

    steps:
    - name: install conan
      run:  pip install conan

    - uses: actions/checkout@v2
      with:
        path: ./nodesetLoader

    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build nodesetLoader
      run: cd ./nodesetLoader && cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON . && cmake --build .

    - name: Test
      shell: cmd
    #  Execute tests defined by the CMake configuration.  
    # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: cd ./nodesetLoader && ctest -C Debug --verbose
